// projects/sa-tools/gke-optimization/binpacker/ui/src/App.tsx
/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import routes from './components/Routes';
import { useRoutes } from 'react-router-dom';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.min.css';
import './styles/CustomToast.css';

const theme = createTheme({
  palette: {
    mode: 'light',
  },
});

function App() {
  const contents = useRoutes(routes);
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <ToastContainer style={{ width: '500px' }} />
      {contents}
    </ThemeProvider>
  );
}

export default App;

// projects/operational-ai-leap/demo_app/ui/src/app/app.component.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, OnInit} from '@angular/core';
import {CommonModule} from '@angular/common';
import {RouterOutlet} from '@angular/router';
import {RouterModule} from '@angular/router';
import {BreakpointObserver, Breakpoints} from '@angular/cdk/layout';

import {MatButtonModule} from '@angular/material/button';
import {MatToolbarModule} from '@angular/material/toolbar';
import {MatIconModule} from '@angular/material/icon';

import {ProductsComponent} from './products/products.component';
import {SnackBarErrorComponent} from './common/SnackBarErrorComponent';

import {MatButtonToggleModule} from '@angular/material/button-toggle';
import {MatCheckboxModule} from '@angular/material/checkbox';
import {MatDividerModule} from '@angular/material/divider';

import {MatMenuModule} from '@angular/material/menu';

import {RoleService} from './services/cymbalshops-api';

import {MatDialog} from '@angular/material/dialog';
import {MarkdownViewerComponent} from './common/markdown-viewer/markdown-viewer.component';
import {HttpClient} from '@angular/common/http';

import {ArchitectureComponent} from './architecture/architecture.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    RouterOutlet,
    RouterModule,
    MatButtonModule,
    MatToolbarModule,
    MatIconModule,
    ProductsComponent,
    MatButtonToggleModule,
    MatCheckboxModule,
    MatDividerModule,
    MatMenuModule,
    MarkdownViewerComponent,
    ArchitectureComponent,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  providers: [SnackBarErrorComponent],
})
export class AppComponent implements OnInit {
  constructor(
    private breakpointObserver: BreakpointObserver,
    private RoleService: RoleService,
    public dialog: MatDialog,
    private http: HttpClient
  ) {}

  isSmallScreen: boolean = false;

  markdownContent = '';

  ngOnInit() {
    this.breakpointObserver
      .observe([Breakpoints.Handset])
      .subscribe(
        () =>
          (this.isSmallScreen = this.breakpointObserver.isMatched(
            Breakpoints.Handset
          ))
      );
  }

  openArchitectureDialog() {
    this.dialog.open(ArchitectureComponent, {
      height: '90%',
      width: '90%',
    });
  }
}

<!--
 Copyright 2026 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<div>
    <mat-toolbar>
        @if(!isSmallScreen) {
            <div>
                <a href="/products"><img src="/assets/cymbal_shops_large.png" alt="Cymbal Shops" class="toolbar-logo" /></a>
            </div>
        } @else {
            <div>
                <a href="/products"><img src="/assets/cymbal_shops_small.png" alt="Cymbal Shops" class="small-toolbar-logo" /></a>
            </div>
        }
        <div class="subtitle">St<i>y</i>leSearch</div>
        <mat-divider [vertical]="true"></mat-divider>

        <span class="toolbar-spacer"></span>

        <div class="powered-by-container">
            <span class="powered-by">Powered By <img src="/assets/alloydb.svg" alt="AlloyDB" class="product-logo" viewBox="0 0 24 24"/> AlloyDB <img src="/assets/vertex_ai.svg" alt="Vertex AI" class="product-logo" viewBox="0 0 24 24"/> Vertex AI</span>
        </div>

        <span class="toolbar-spacer"></span>

        <mat-divider [vertical]="true"></mat-divider>
        <button mat-button (click)="openArchitectureDialog()"><span class="architecture">Architecture</span></button>
    </mat-toolbar>
    <body>
        <router-outlet></router-outlet>
    </body>
</div>
